# The Y-level threshold below which players will be teleported
void-y-level: 0

# Spawn locations saved with custom names
spawn-locations:
  exampleSpawn:
    world: world
    x: 0
    y: 80
    z: 0
