name: NoFallPlugin
version: '1.0'
main: Nine.Studio.NoFall.NoFallPlugin
api-version: '1.21'
commands:
  voidLocation:
    description: Manage void locations.
    usage: /voidLocation <spawnName> | /voidLocation remove <spawnName> | /voidLocation list
